# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: cristiano100.roforge
PackageVersion: "0.1"
InstallerType: portable
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/cristiano100/roforge/releases/latest/download/Roforge.exe
  InstallerSha256: 52078C951B5995B1020B63DD7C0BDCB33037FE2E9102D1675A80ADECC85651CD
ManifestType: installer
ManifestVersion: 1.5.0
